import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-between bg-black text-white">
            <div className="w-1/4">
              <Image width={100} height={100} src='/assets/logo.jpg' alt=""/>
            </div>
            <div className="flex justify-around w-2/3 items-center">
              <div className="flex justify-between">
                  <ul className="flex gap-20">
                    <li className="hover:bg-zinc-200 hover:text-black p-10">
                      Home
                    </li>
                    <li className="hover:bg-zinc-200 hover:text-black p-10">
                      About
                    </li>
                    <li className="hover:bg-zinc-200 hover:text-black p-10">
                        Contact
                    </li>
                    <li className="hover:bg-zinc-200 hover:text-black p-10">
                        Services
                    </li>
                  </ul>
              </div>
              <div>
                  <button className="border-2 border-zinc-200 p-5 hover:bg-zinc-200 hover:text-black hover:rounded-lg hover:duration-300 ease-in">
                    Click me
                  </button>
              </div>
            </div>
        </div>
        {children}
      </body>
    </html>
  );
}
